theme = "gruvbox_dark_soft"

[editor]
idle-timeout = 50
bufferline = "multiple"
line-number = "relative"
true-color = true
rulers = [120]
lsp.display-inlay-hints = true
popup-border = "all"

[keys.normal]
A-w = ":write"

[keys.normal."space"]
";" = "save_selection"
